<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HaloVPN.Contracts\HaloVPN.Contracts.csproj" />
    <ProjectReference Include="..\HaloVPN.Platform.Windows\HaloVPN.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
